version: '3'
services:

  ardigen-github-search-api:
    image: ardigen-github-search-api
    container_name: ardigen-github-search-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - ${ARDIGEN_GITHUB_SEARC_API_PORT}:3000
    networks:
      - ardigen-github-search
  
  ardigen-github-search-client:
    image: ardigen-github-search-client
    container_name: ardigen-github-search-client
    build:
      context: client
      args:
        - CONFIG=${ARDIGEN_GITHUB_SEARC_CLIENT_CONFIG}
      dockerfile: Dockerfile
    ports:
      - ${ARDIGEN_GITHUB_SEARC_CLIENT_PORT}:80
    networks:
      - ardigen-github-search
    depends_on:
      - ardigen-github-search-api

networks:
  ardigen-github-search: